services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      - "${ADMIN_PORT}:81"  # Admin UI
    volumes:
      - "${DATA}:/data"
      - "${LETSENCRYPT}:/etc/letsencrypt"
